### ISSUE TITLE
[Bug] Text on labels not x or y centered

### ISSUE THREAD

**Issue by theoccurrence** [PoomSmart/BlurryBadges#3]
It's a bit more noticeable with two digit numbers:
![image](https://github.com/PoomSmart/BlurryBadges/assets/16444679/cbc767a0-4dab-4e7c-a370-e85de35200c4)

It's even more noticeable with smaller fonts:
![image](https://github.com/PoomSmart/BlurryBadges/assets/16444679/3b533259-13fd-4572-bdee-e27e9fdccdfc)

iPhone 12 Pro Max iOS 16.4

**Comment by PoomSmart** [comment]
Fixed in v1.4.5

**Comment by theoccurrence** [comment]
Can confirm. Good work 👍
