### ISSUE TITLE
Colored badges on homescreen make Springboard increasingly laggy

### ISSUE THREAD

**Issue by theoccurrence** [PoomSmart/BlurryBadges#4]
Having apps with colored badges on a homecreen page makes paging really laggy over time. It's almost not noticeable directly after a respring, but it quickly gets increasingly worse. Activating a focus mode which hides badges completely fixes this issue. Scrolling to a page without badges doesn't lag either. It clearly correlates with the presence of colored badges.

Please excuse the quality, iPad camera. Also I couldn't upload the video here for some reason, so I had to use an external hoster.

https://imgur.com/a/TMYslv8

iPhone 12 Pro Max, iOS 16.4

**Comment by theoccurrence** [comment]
This is how laggy it gets after a couple of hours: 

https://github.com/PoomSmart/BlurryBadges/assets/16444679/51742852-9167-462b-90ea-c99038d9d78f

The lag is also very noticeable when going to the homescreen page by closing an app or unlocking the device. It's only about 0.4 to 0.5 seconds of lag when it gets bad, but it quickly adds up over the day and it's ugly.

EDIT: I should note it makes a big difference wether I have low power mode enabled, or not. Without LPM enabled it is better and it takes longer to get really noticeable.

**Comment by PoomSmart** [comment]
@theoccurrence Tweak list?

**Comment by theoccurrence** [comment]
> @theoccurrence Tweak list?

April
Atria
Barmoji
Battery Buddy
Cask 3
CCSupport
Cylinder Remade
EFM
Emoji Port
Eneko
Lynx 2
NiceBarX
QuickActions
RemoveConfideltial
Rune
SettingsRevamp
Snapper 3
Snowboard
Stella
Velvet 2

**Comment by PoomSmart** [comment]
Should be fixed in v1.5.0
